// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuQ92ieG07kd7z85x967BKXDJbyKbBA2E',
    appId: '1:57717820161:web:984baa6dc719c854ee2900',
    messagingSenderId: '57717820161',
    projectId: 'growsistant-75bd8',
    authDomain: 'growsistant-75bd8.firebaseapp.com',
    storageBucket: 'growsistant-75bd8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCedeQRGi5Idf3s7eb1JchBSoEtHhdiUM',
    appId: '1:57717820161:android:892cf8c92f130773ee2900',
    messagingSenderId: '57717820161',
    projectId: 'growsistant-75bd8',
    storageBucket: 'growsistant-75bd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYlflMQtYmAyrxagY3gy6frAAH_f6N4s0',
    appId: '1:57717820161:ios:050e4f22673a857aee2900',
    messagingSenderId: '57717820161',
    projectId: 'growsistant-75bd8',
    storageBucket: 'growsistant-75bd8.firebasestorage.app',
    iosBundleId: 'com.growsistant.growsistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYlflMQtYmAyrxagY3gy6frAAH_f6N4s0',
    appId: '1:57717820161:ios:050e4f22673a857aee2900',
    messagingSenderId: '57717820161',
    projectId: 'growsistant-75bd8',
    storageBucket: 'growsistant-75bd8.firebasestorage.app',
    iosBundleId: 'com.growsistant.growsistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuQ92ieG07kd7z85x967BKXDJbyKbBA2E',
    appId: '1:57717820161:web:f69efecef147cc13ee2900',
    messagingSenderId: '57717820161',
    projectId: 'growsistant-75bd8',
    authDomain: 'growsistant-75bd8.firebaseapp.com',
    storageBucket: 'growsistant-75bd8.firebasestorage.app',
  );
}
